/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type DateOnly, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Bad request error
 */
export interface BadRequestError extends ApiError, ErrorResponse, Parsable {
}
export type BadRequestError_code = (typeof BadRequestError_codeObject)[keyof typeof BadRequestError_codeObject];
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BadRequestError}
 */
// @ts-ignore
export function createBadRequestErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBadRequestError;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WeatherForecast}
 */
// @ts-ignore
export function createWeatherForecastFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWeatherForecast;
}
/**
 * The deserialization information for the current model
 * @param BadRequestError The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBadRequestError(badRequestError: Partial<BadRequestError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoErrorResponse(badRequestError),
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorResponse.code = n.getStringValue(); },
        "details": n => { errorResponse.details = n.getStringValue(); },
        "message": n => { errorResponse.messageEscaped = n.getStringValue(); },
        "requestId": n => { errorResponse.requestId = n.getStringValue(); },
        "timestamp": n => { errorResponse.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WeatherForecast The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWeatherForecast(weatherForecast: Partial<WeatherForecast> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "date": n => { weatherForecast.date = n.getDateOnlyValue(); },
        "id": n => { weatherForecast.id = n.getStringValue(); },
        "location": n => { weatherForecast.location = n.getStringValue(); },
        "summary": n => { weatherForecast.summary = n.getStringValue(); },
        "temperatureC": n => { weatherForecast.temperatureC = n.getNumberValue(); },
        "temperatureF": n => { weatherForecast.temperatureF = n.getNumberValue(); },
    }
}
/**
 * Standard error response
 */
export interface ErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Error code
     */
    code?: string | null;
    /**
     * Additional error details
     */
    details?: string | null;
    /**
     * Human-readable error message
     */
    messageEscaped?: string | null;
    /**
     * Request ID for tracking
     */
    requestId?: string | null;
    /**
     * Timestamp when error occurred
     */
    timestamp?: Date | null;
}
/**
 * Serializes information the current object
 * @param BadRequestError The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBadRequestError(writer: SerializationWriter, badRequestError: Partial<BadRequestError> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!badRequestError || isSerializingDerivedType) { return; }
    serializeErrorResponse(writer, badRequestError, isSerializingDerivedType)
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", errorResponse.code);
    writer.writeStringValue("details", errorResponse.details);
    writer.writeStringValue("message", errorResponse.messageEscaped);
    writer.writeStringValue("requestId", errorResponse.requestId);
    writer.writeDateValue("timestamp", errorResponse.timestamp);
    writer.writeAdditionalData(errorResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WeatherForecast The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWeatherForecast(writer: SerializationWriter, weatherForecast: Partial<WeatherForecast> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!weatherForecast || isSerializingDerivedType) { return; }
    writer.writeDateOnlyValue("date", weatherForecast.date);
    writer.writeStringValue("id", weatherForecast.id);
    writer.writeStringValue("location", weatherForecast.location);
    writer.writeStringValue("summary", weatherForecast.summary);
    writer.writeNumberValue("temperatureC", weatherForecast.temperatureC);
    writer.writeNumberValue("temperatureF", weatherForecast.temperatureF);
    writer.writeAdditionalData(weatherForecast.additionalData);
}
/**
 * Represents a weather forecast for a specific location and date
 */
export interface WeatherForecast extends AdditionalDataHolder, Parsable {
    /**
     * Date of the weather forecast
     */
    date?: DateOnly | null;
    /**
     * Unique identifier for the weather forecast
     */
    id?: string | null;
    /**
     * Geographic location of the forecast
     */
    location?: string | null;
    /**
     * Weather summary description
     */
    summary?: string | null;
    /**
     * Temperature in Celsius
     */
    temperatureC?: number | null;
    /**
     * Temperature in Fahrenheit (calculated)
     */
    temperatureF?: number | null;
}
export const BadRequestError_codeObject = {
    BAD_REQUEST: "BAD_REQUEST",
} as const;
/* tslint:enable */
/* eslint-enable */
