/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestErrorFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, createWeatherForecastFromDiscriminatorValue, serializeWeatherForecast, type BadRequestError, type ErrorResponse, type WeatherForecast } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /weatherforecast
 */
export interface WeatherforecastRequestBuilder extends BaseRequestBuilder<WeatherforecastRequestBuilder> {
    /**
     * Get all weather forecasts
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WeatherForecast[]>}
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WeatherForecast[] | undefined>;
    /**
     * Add a new weather forecast
     * @param body Represents a weather forecast for a specific location and date
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WeatherForecast>}
     * @throws {BadRequestError} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     post(body: WeatherForecast, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WeatherForecast | undefined>;
    /**
     * Get all weather forecasts
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Add a new weather forecast
     * @param body Represents a weather forecast for a specific location and date
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WeatherForecast, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WeatherforecastRequestBuilderUriTemplate = "{+baseurl}/weatherforecast";
/**
 * Metadata for all the requests in the request builder.
 */
export const WeatherforecastRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WeatherforecastRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createWeatherForecastFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WeatherforecastRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWeatherForecastFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWeatherForecast,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
